apiVersion: v1
kind: Service
metadata:
  name: message-generator
  labels:
    app: message-generator
spec:
  selector:
    app: message-generator
  ports:
  - name: http
    port: 80
    targetPort: 80